{
 "title": "GOD Jenkins",
 "description": "Shows main statistics for Jenkins JVM and last builds",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU resources",
   "type": "graph",
   "description": "The system load on the Jenkins master as reported by the JVM’s Operating System JMX bean. The calculation of system load is operating system dependent. Typically this is the sum of the number of processes that are currently running plus the number that are waiting to run. This is typically comparable against the number of CPU cores.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_load" }
   ]
  },
  {
   "title": "JVM heap size",
   "type": "stat",
   "description": "The total amount of memory that the Jenkins master JVM is currently using.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "description": "The total memory usage in %.",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_memory_total_used / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score " }
   ]
  },
  {
   "title": "Total nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_count_value" }
   ]
  },
  {
   "title": "Active plugin",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "vm_uptime_milliseconds" }
   ]
  },
  {
   "title": "Online nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_online_value" }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Failed plugins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "Inactive plugins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "description": "The rate at which jobs are queued and the total time they spend in the build queue.",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration", "legendFormat": "{{job}} - {{quantile}}" }
   ]
  },
  {
   "title": "Total executors",
   "type": "singlestat",
   "description": "The number of executors available to Jenkins. This is corresponds to the sum of all the executors of all the on-line nodes.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_count_value" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "description": "The number of jobs that are in the Jenkins build queue.",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "description": "The number of executors available to Jenkins that are not currently in use.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "description": "The number of executors available to Jenkins that are currently in use.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Last build statistic",
   "type": "table",
   "description": "Statistics for all last builds in Jenkins",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(default_jenkins_builds_success_build_count / on (jenkins_job, jenkins_job) ( default_jenkins_builds_success_build_count  + default_jenkins_builds_failed_build_count)) by (jenkins_job)"
    },
    {
     "expr": "sum(default_jenkins_builds_last_build_duration_milliseconds) by (jenkins_job)"
    },
    {
     "expr": "avg(default_jenkins_builds_last_build_result) by (jenkins_job)"
    },
    {
     "expr": "sum(default_jenkins_builds_last_build_start_time_milliseconds) by (jenkins_job)"
    },
    {
     "expr": "sum(default_jenkins_builds_last_build_tests_total) by (jenkins_job)"
    },
    {
     "expr": "sum(default_jenkins_builds_last_build_tests_failing) by (jenkins_job)"
    }
   ]
  }
 ]
}